// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SunniNooriMasjidAPI.Data.MasjidDbContext;

#nullable disable

namespace SunniNooriMasjidAPI.Migrations
{
    [DbContext(typeof(SunniNooriMasjidDbContext))]
    [Migration("20250102150848_RenameUserIdToMemberId")]
    partial class RenameUserIdToMemberId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SunniNooriMasjidAPI.Data.Entities.Masjidgullak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CollectionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MemberId" }, "MemberId");

                    b.ToTable("masjidgullak", (string)null);
                });

            modelBuilder.Entity("SunniNooriMasjidAPI.Data.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FatherName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("fatherName");

                    b.Property<DateTime?>("JoiningDate")
                        .HasColumnType("date")
                        .HasColumnName("joiningDate");

                    b.Property<string>("MemberPic")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("memberPic");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("mobileNumber");

                    b.Property<int?>("MohallaId")
                        .HasColumnType("int")
                        .HasColumnName("mohalla_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MohallaId" }, "fk_mohalla_id");

                    b.HasIndex(new[] { "RoleId" }, "fk_role_id");

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("SunniNooriMasjidAPI.Data.Entities.Mohalla", b =>
                {
                    b.Property<int>("MohallaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mohalla_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MohallaId"));

                    b.Property<string>("MohallaName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mohalla_name");

                    b.Property<int?>("Population")
                        .HasColumnType("int")
                        .HasColumnName("population");

                    b.Property<int?>("VillageId")
                        .HasColumnType("int")
                        .HasColumnName("village_id");

                    b.HasKey("MohallaId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "VillageId" }, "village_id");

                    b.ToTable("mohallas", (string)null);
                });

            modelBuilder.Entity("SunniNooriMasjidAPI.Data.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Imam','President','Secretary','Treasurer','Member','Other')")
                        .HasColumnName("role_name")
                        .HasDefaultValueSql("'Member'");

                    b.HasKey("RoleId")
                        .HasName("PRIMARY");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("SunniNooriMasjidAPI.Data.Entities.Sadqamember", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<int?>("AddedBy")
                        .HasColumnType("int");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Caste")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FatherName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Mohalla")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp");

                    b.HasKey("MemberId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AddedBy" }, "AddedBy");

                    b.ToTable("sadqamember", (string)null);
                });

            modelBuilder.Entity("SunniNooriMasjidAPI.Data.Entities.Village", b =>
                {
                    b.Property<int>("VillageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("village_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VillageId"));

                    b.Property<decimal?>("AreaSize")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("area_size");

                    b.Property<DateTime?>("EstablishedDate")
                        .HasColumnType("date")
                        .HasColumnName("established_date");

                    b.Property<int?>("TotalPopulation")
                        .HasColumnType("int")
                        .HasColumnName("total_population");

                    b.Property<string>("VillageName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("village_name");

                    b.HasKey("VillageId")
                        .HasName("PRIMARY");

                    b.ToTable("villages", (string)null);
                });

            modelBuilder.Entity("SunniNooriMasjidAPI.Data.Entities.Villagemember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Caste")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("caste");

                    b.Property<string>("FatherName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("fatherName");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("lastName");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("member_id");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("mobileNumber");

                    b.Property<int?>("MohallaId")
                        .HasColumnType("int")
                        .HasColumnName("mohalla_id");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime")
                        .HasColumnName("paymentDate");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MohallaId" }, "mohalla_id");

                    b.ToTable("villagemember", (string)null);
                });

            modelBuilder.Entity("SunniNooriMasjidAPI.Data.Entities.Masjidgullak", b =>
                {
                    b.HasOne("SunniNooriMasjidAPI.Data.Entities.Member", "Member")
                        .WithMany("Masjidgullaks")
                        .HasForeignKey("MemberId")
                        .HasConstraintName("masjidgullak_ibfk_1");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("SunniNooriMasjidAPI.Data.Entities.Member", b =>
                {
                    b.HasOne("SunniNooriMasjidAPI.Data.Entities.Mohalla", "Mohalla")
                        .WithMany("Members")
                        .HasForeignKey("MohallaId")
                        .HasConstraintName("fk_mohalla_id");

                    b.HasOne("SunniNooriMasjidAPI.Data.Entities.Role", "Role")
                        .WithMany("Members")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("fk_role_id");

                    b.Navigation("Mohalla");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SunniNooriMasjidAPI.Data.Entities.Mohalla", b =>
                {
                    b.HasOne("SunniNooriMasjidAPI.Data.Entities.Village", "Village")
                        .WithMany("Mohallas")
                        .HasForeignKey("VillageId")
                        .HasConstraintName("mohallas_ibfk_1");

                    b.Navigation("Village");
                });

            modelBuilder.Entity("SunniNooriMasjidAPI.Data.Entities.Sadqamember", b =>
                {
                    b.HasOne("SunniNooriMasjidAPI.Data.Entities.Member", "AddedByNavigation")
                        .WithMany("Sadqamembers")
                        .HasForeignKey("AddedBy")
                        .HasConstraintName("sadqamember_ibfk_1");

                    b.Navigation("AddedByNavigation");
                });

            modelBuilder.Entity("SunniNooriMasjidAPI.Data.Entities.Villagemember", b =>
                {
                    b.HasOne("SunniNooriMasjidAPI.Data.Entities.Member", "IdNavigation")
                        .WithOne("Villagemember")
                        .HasForeignKey("SunniNooriMasjidAPI.Data.Entities.Villagemember", "Id")
                        .IsRequired()
                        .HasConstraintName("villagemember_ibfk_2");

                    b.HasOne("SunniNooriMasjidAPI.Data.Entities.Mohalla", "Mohalla")
                        .WithMany("Villagemembers")
                        .HasForeignKey("MohallaId")
                        .HasConstraintName("villagemember_ibfk_1");

                    b.Navigation("IdNavigation");

                    b.Navigation("Mohalla");
                });

            modelBuilder.Entity("SunniNooriMasjidAPI.Data.Entities.Member", b =>
                {
                    b.Navigation("Masjidgullaks");

                    b.Navigation("Sadqamembers");

                    b.Navigation("Villagemember");
                });

            modelBuilder.Entity("SunniNooriMasjidAPI.Data.Entities.Mohalla", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Villagemembers");
                });

            modelBuilder.Entity("SunniNooriMasjidAPI.Data.Entities.Role", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("SunniNooriMasjidAPI.Data.Entities.Village", b =>
                {
                    b.Navigation("Mohallas");
                });
#pragma warning restore 612, 618
        }
    }
}
